package main;

import config.Session;
import config.config;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class editprofileuser extends javax.swing.JPanel {   
    
  
    public editprofileuser() {
    initComponents();
    }
    
    
            public void loadUserData() {
        Session sess = Session.getInstance();
        // I-set ang text fields base sa Session data
        jTextField2.setText(sess.getFullname());
        jTextField3.setText(sess.getUsername());
        jTextField4.setText(sess.getEmail());
        jTextField5.setText(sess.getContact());
        jPasswordField1.setText(sess.getPassword());
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 235, 215));
        setPreferredSize(new java.awt.Dimension(790, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel1.setText("EDIT PROFILE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jTextField1.setText("Account type : User ");
        jTextField1.setEnabled(false);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 150, 20));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, 20));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 150, 20));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, 20));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 150, 20));

        jPasswordField1.setText("Password");
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 150, 20));

        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel2.setText("Password ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel3.setText("Full Name  :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setText("Username : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel5.setText("Email :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel6.setText("Contact : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        config conf = new config();
        Session sess = Session.getInstance();
        
        String fn = jTextField2.getText();
        String un = jTextField3.getText();
        String em = jTextField4.getText();
        String cn = jTextField5.getText();
        String ps = new String(jPasswordField1.getPassword());

       String query = "UPDATE accounts SET fullname = ?, email = ?, password = ? WHERE a_id = ?";
        
        try {
            // Gamita ang saktong params base sa imong config.addRecord method
            conf.addRecord(query, fn, em, ps, sess.getA_Id());
            
            // I-update ang Session
            sess.setFullname(fn);
            sess.setUsername(un);
            sess.setEmail(em);
            sess.setContact(cn);
            sess.setPassword(ps);

            JOptionPane.showMessageDialog(this, "Updated Successfully!");
            goBack(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     goBack(false);
    }                                        

    private void goBack(boolean refresh) {
        Container parent = this.getParent();
        if (parent != null && parent.getLayout() instanceof CardLayout) {
            userdashboard ds = (userdashboard) SwingUtilities.getWindowAncestor(this);
            if (refresh) {
                ds.accountprofileu11.setUserData(); // I-refresh ang labels sa Profile page
            }
            CardLayout cl = (CardLayout) parent.getLayout();
            cl.show(parent, "card2"); // Card2 = Account Profile
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
