/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Font;
import java.awt.Image;

/**
 *
 * @author PC
 */
public class landingpage extends javax.swing.JFrame {

    /**
     * Creates new form landingpage
     */
    public landingpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        systemname = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        navigatorbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 235, 215));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(250, 235, 215));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 180, 140)));
        header.setMaximumSize(new java.awt.Dimension(32767, 80));
        header.setPreferredSize(new java.awt.Dimension(1000, 80));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(92, 64, 51));
        login.setForeground(java.awt.Color.white);
        login.setText("LOGIN");
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(92, 64, 51)));
        login.setBorderPainted(false);
        login.setFocusPainted(false);
        login.setPreferredSize(new java.awt.Dimension(100, 30));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        header.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 125, 47));

        signup.setBackground(new java.awt.Color(92, 64, 51));
        signup.setForeground(java.awt.Color.white);
        signup.setText("SIGN UP");
        signup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(92, 64, 51)));
        signup.setBorderPainted(false);
        signup.setFocusPainted(false);
        signup.setPreferredSize(new java.awt.Dimension(100, 30));
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        header.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 125, 47));

        systemname.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        systemname.setForeground(new java.awt.Color(92, 64, 51));
        systemname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        systemname.setText("PAW PRINTS");
        systemname.setPreferredSize(new java.awt.Dimension(200, 30));
        header.add(systemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 160, 50));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        header.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 60));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 90));

        navigatorbar.setBackground(new java.awt.Color(250, 235, 215));
        navigatorbar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(210, 180, 140)));
        navigatorbar.setForeground(new java.awt.Color(210, 180, 140));
        navigatorbar.setMaximumSize(new java.awt.Dimension(32767, 40));
        navigatorbar.setPreferredSize(new java.awt.Dimension(100, 70));
        navigatorbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Home");
        navigatorbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 25, 42, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contact");
        navigatorbar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 25, 100, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sponsor a Pet");
        navigatorbar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, 100, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tips");
        navigatorbar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 25, 100, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("About Us");
        navigatorbar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 25, 100, 20));

        getContentPane().add(navigatorbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 70));

        main.setBackground(new java.awt.Color(250, 235, 215));
        main.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 40, 20, 40));
        main.setPreferredSize(new java.awt.Dimension(900, 400));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(92, 64, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>  <div style=\"text-align: center; font-family: 'Georgia', serif; color: #5C4033; padding: 10px;\">   <span style=\"font-size: 24pt; font-weight: bold; text-shadow: 3px 3px 5px #A9A9A9;\">     Find Your<br>     <span style=\"font-size: 32pt; color: #8B4513;\">Perfect Friend</span>   </span>  </div> </html>");
        jLabel7.setPreferredSize(new java.awt.Dimension(450, 40));
        main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 380, 160));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 2, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Give a loving home to a furry friend today!");
        jLabel8.setPreferredSize(new java.awt.Dimension(400, 25));
        main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 60));

        jButton1.setBackground(new java.awt.Color(210, 180, 140));
        jButton1.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 16));
        jButton1.setForeground(new java.awt.Color(92, 64, 51));
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setText("<html>EXPLORE&nbsp;&nbsp;<span style='font-size:22px;'>&#8594;</span></html>");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(92, 64, 51), 2, true));
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(92, 64, 51), 2, true)); // rounded corners
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        main.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 80));

        jPanel4.setBackground(new java.awt.Color(92, 64, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        main.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 212, 320, 2));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/four-happy-petstwo-dogs-two-600nw-2600858177-removebg-preview (1).png"))); // NOI18N
        main.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 480, 220));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pets-about-free-img-removebg-preview.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        main.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 290, 450));

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1000, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
         new login().setVisible(true);
              this.dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
          new registration().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new java.awt.Color(210, 180, 140));    }//GEN-LAST:event_jButton1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landingpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton login;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel main;
    private javax.swing.JPanel navigatorbar;
    private javax.swing.JButton signup;
    private javax.swing.JLabel systemname;
    // End of variables declaration//GEN-END:variables
}
